name: Deploy to Server
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              env:
                  HOST: ${{ secrets.SERVER_HOST }}
                  USERNAME: ${{ secrets.SERVER_USERNAME }}
                  PASSWORD: ${{ secrets.SERVER_PASSWORD }}
              with:
                  host: ${{ env.HOST }}
                  username: ${{ env.USERNAME }}
                  password: ${{ env.PASSWORD }}
                  script: |
                      cd /var/www/html
                      git pull origin main
                      npm install
                      npm run build
